name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.120.26.81.229 }}
          SERVER_USER: ${{ secrets.root }}
          SERVER_PASSWORD: ${{ secrets.Yuanqiyiliao2024 }}
        run: |
          scp -r build/* $SERVER_USER@$SERVER_IP:/usr/share/nginx/html/
